#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draniki.Project.Draniki.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Text;
    using Sitecore.Globalization;
    using Sitecore.Data;
    using Sitecore.Data.Items;
 
    using System.CodeDom.Compiler;
    
    
    /// <summary>
    /// IArticle Interface
    /// <para>Path: /sitecore/templates/Draniki/Project/Draniki/DataSources/Article</para>
    /// <para>ID: 327c1a09-8a36-47bb-9005-b0d67440d49b</para>
    /// </summary>
    [SitecoreType(TemplateId="327c1a09-8a36-47bb-9005-b0d67440d49b")]
    public partial interface IArticle: IGlassBase
    {
        
        /// <summary>
        /// The  field.
        /// <para>Field Type: Multi-Line Text</para>
        /// <para>Field ID: d5c476e1-6fd1-40cc-9c98-1671abbddd6b</para>
        /// </summary>
        [SitecoreField("Description")]
        string Description {get; set;}
        
        /// <summary>
        /// The  field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 8b249dbe-f06a-4c84-b085-3c0cb9da814d</para>
        /// </summary>
        [SitecoreField("Title")]
        string Title {get; set;}
        
    }
    
    
    /// <summary>
    /// Article Class
    /// <para>Path: /sitecore/templates/Draniki/Project/Draniki/DataSources/Article</para>
    /// <para>ID: 327c1a09-8a36-47bb-9005-b0d67440d49b</para>
    /// </summary>
    [SitecoreType(TemplateId="327c1a09-8a36-47bb-9005-b0d67440d49b")]
    public partial class Article: GlassBase, IArticle
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/Draniki/Project/Draniki/DataSources/Article
        /// </summary>
        public const string TemplateId = "327c1a09-8a36-47bb-9005-b0d67440d49b";

        /// <summary>
        /// The Description field.
        /// <para>Field Type: Multi-Line Text</para>
        /// <para>Field ID: d5c476e1-6fd1-40cc-9c98-1671abbddd6b</para>
        /// </summary>
        [SitecoreField("Description")]
        public string Description {get; set;}
        public const string DescriptionFieldId = "d5c476e1-6fd1-40cc-9c98-1671abbddd6b";
        public const string DescriptionFieldName = "Description";
        
        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 8b249dbe-f06a-4c84-b085-3c0cb9da814d</para>
        /// </summary>
        [SitecoreField("Title")]
        public string Title {get; set;}
        public const string TitleFieldId = "8b249dbe-f06a-4c84-b085-3c0cb9da814d";
        public const string TitleFieldName = "Title";
        
    }
    
    
    /// <summary>
    /// IArticleList Interface
    /// <para>Path: /sitecore/templates/Draniki/Project/Draniki/DataSources/Article List</para>
    /// <para>ID: 299052a0-bd67-44e1-acd4-60e5f0e8e18a</para>
    /// </summary>
    [SitecoreType(TemplateId="299052a0-bd67-44e1-acd4-60e5f0e8e18a")]
    public partial interface IArticleList: IGlassBase
    {
        
        /// <summary>
        /// The  field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: a543aca3-e5c7-46c4-98cc-2cea9436cc96</para>
        /// </summary>
        [SitecoreField("Articles")]
        IEnumerable<Guid> Articles {get; set;}
        
        /// <summary>
        /// The  field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 7a3972c7-400a-4b22-9be0-4982b438184e</para>
        /// </summary>
        [SitecoreField("Title")]
        string Title {get; set;}
        
    }
    
    
    /// <summary>
    /// ArticleList Class
    /// <para>Path: /sitecore/templates/Draniki/Project/Draniki/DataSources/Article List</para>
    /// <para>ID: 299052a0-bd67-44e1-acd4-60e5f0e8e18a</para>
    /// </summary>
    [SitecoreType(TemplateId="299052a0-bd67-44e1-acd4-60e5f0e8e18a")]
    public partial class ArticleList: GlassBase, IArticleList
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/Draniki/Project/Draniki/DataSources/Article List
        /// </summary>
        public const string TemplateId = "299052a0-bd67-44e1-acd4-60e5f0e8e18a";

        /// <summary>
        /// The Articles field.
        /// <para>Field Type: Multilist</para>
        /// <para>Field ID: a543aca3-e5c7-46c4-98cc-2cea9436cc96</para>
        /// </summary>
        [SitecoreField("Articles")]
        public IEnumerable<Guid> Articles {get; set;}
        public const string ArticlesFieldId = "a543aca3-e5c7-46c4-98cc-2cea9436cc96";
        public const string ArticlesFieldName = "Articles";
        
        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 7a3972c7-400a-4b22-9be0-4982b438184e</para>
        /// </summary>
        [SitecoreField("Title")]
        public string Title {get; set;}
        public const string TitleFieldId = "7a3972c7-400a-4b22-9be0-4982b438184e";
        public const string TitleFieldName = "Title";
        
    }
    
    
    /// <summary>
    /// INewsFeedSubscription Interface
    /// <para>Path: /sitecore/templates/Draniki/Project/Draniki/DataSources/News Feed Subscription</para>
    /// <para>ID: 7174adb0-6e20-4ad0-b5d2-3bf43de2e9c1</para>
    /// </summary>
    [SitecoreType(TemplateId="7174adb0-6e20-4ad0-b5d2-3bf43de2e9c1")]
    public partial interface INewsFeedSubscription: IGlassBase
    {
        
        /// <summary>
        /// The  field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 2b01f0ce-be19-40fc-9c75-8f90338fe7aa</para>
        /// </summary>
        [SitecoreField("Email Label")]
        string EmailLabel {get; set;}
        
        /// <summary>
        /// The  field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ead381ae-5047-4e4b-b164-122371133483</para>
        /// </summary>
        [SitecoreField("Title")]
        string Title {get; set;}
        
    }
    
    
    /// <summary>
    /// NewsFeedSubscription Class
    /// <para>Path: /sitecore/templates/Draniki/Project/Draniki/DataSources/News Feed Subscription</para>
    /// <para>ID: 7174adb0-6e20-4ad0-b5d2-3bf43de2e9c1</para>
    /// </summary>
    [SitecoreType(TemplateId="7174adb0-6e20-4ad0-b5d2-3bf43de2e9c1")]
    public partial class NewsFeedSubscription: GlassBase, INewsFeedSubscription
    {
        /// <summary>
        /// The TemplateId string for /sitecore/templates/Draniki/Project/Draniki/DataSources/News Feed Subscription
        /// </summary>
        public const string TemplateId = "7174adb0-6e20-4ad0-b5d2-3bf43de2e9c1";

        /// <summary>
        /// The Email Label field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: 2b01f0ce-be19-40fc-9c75-8f90338fe7aa</para>
        /// </summary>
        [SitecoreField("Email Label")]
        public string EmailLabel {get; set;}
        public const string EmailLabelFieldId = "2b01f0ce-be19-40fc-9c75-8f90338fe7aa";
        public const string EmailLabelFieldName = "Email Label";
        
        /// <summary>
        /// The Title field.
        /// <para>Field Type: Single-Line Text</para>
        /// <para>Field ID: ead381ae-5047-4e4b-b164-122371133483</para>
        /// </summary>
        [SitecoreField("Title")]
        public string Title {get; set;}
        public const string TitleFieldId = "ead381ae-5047-4e4b-b164-122371133483";
        public const string TitleFieldName = "Title";
        
    }
    
}